[versions]
# Libraries
junit = "4.13.+"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
jetbrains-annotations = "org.jetbrains:annotations:24.0.+"
# junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
javolution = "org.javolution:javolution:5.3.1"